---
- name: this is a playbook for creating a user ui§ning variables
  hosts: all
  become: yes
  vars:
    user: sunny
  tasks:
    - name: creating user {{user}}
      user:
        name: "{{user}}"
