---
- name: This playbook creates multiple users
  hosts: all
  become: true
  tasks:
    - name: creating multiple users
      user: name='{{item}}' state=present
      with_items:
        - Raj
        - sai
        - neha
        - hansi
