---
- name: This the playbook for installing and starting httpd service using notify and handlers
  hosts: all
  become: true
  tasks:
    - name: installing httpd service
      yum:
        name: httpd
        state: installed
      notify: starting httpd service

  handlers:
    - name: starting httpd service
      service:
        name: httpd
        state: started
