---
- name: installing multiple packages
  hosts: all
  become: true
  tasks:
    - name: install multiple packages
      yum:
        name: ["git","tree","docker*"]
        state: installed


        
